version: "1"
rules:
  - base: master
    upstream: mazipan:master
    mergeMethod: hardreset # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"