savePrefix: ''
blockExoticSubdeps: true
minimumReleaseAge: 1440 # In minutes -- 1440 minutes = 1 day
trustPolicy: 'no-downgrade'
trustPolicyExclude:
  - chokidar@4.0.3
allowBuilds:
  '@firebase/util': true
  protobufjs: true
