export default {
  VERSION: '1.0.0',
  FAVORITE: 'FAV',
  LAST_READ: 'LAST_READ',
  SETTING_THEME: 'THEME',
  SETTING_TRANSLATION: 'SET_TRANS',
  SETTING_TAFSIR: 'SET_TAFSIR',
  SETTING_MUQADDIMAH: 'SET_MQD'
}
