export default {
  ALL_SURAH: 'ALL_SURAH',
  SURAH_BY_ID: (id) => `SURAH_${id}`,
  FAVORITE: 'FAV',
  LAST_READ: 'LAST_READ',
  AYAT_KURSI: 'AYAT_KURSI',
  ASMAUL_HUSNA: 'ASMAUL_HUSNA',
  DAILY_DOA: 'DAILY_DOA',
  SETTING_THEME: 'THEME',
  SETTING_TRANSLATION: 'SET_TRANS',
  SETTING_TAFSIR: 'SET_TAFSIR'
}
