export const staticUrls = [
	'/',
	'/about/',
	'/all-surah/',
	'/asmaul-husna/',
	'/ayat-kursi/',
	'/daily-doa/',
	'/jadwal-sholat/',
	'/juz-amma/',
	'/kebijakan-privasi/',
	'/ketentuan-layanan/',
	'/settings/',
	'/surah-makkiyah/',
	'/surah-madaniyah/',
	'/sync/',
	'/tahlil/',
	'/tasbih/',
	'/wirid/'
];
